import { ImagePlus, Palette } from "lucide-react";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type PageIdentity = { logoUrl: string | null; logoPath: string | null; primaryColor: string; accentColor: string; backgroundColor: string };
export default function LandingIdentityEditor({ value, onChange }: { value: PageIdentity; onChange: (value: PageIdentity) => void }) {
  const upload = trpc.landing.uploadImage.useMutation({ onSuccess: image => { onChange({ ...value, logoUrl: image.url, logoPath: image.path }); toast.success("Logo da página carregada"); }, onError: error => toast.error(error.message) });
  const file = (input?: File) => { if (!input) return; if (!["image/jpeg", "image/png", "image/webp"].includes(input.type)) return toast.error("Use JPG, PNG ou WEBP."); const reader = new FileReader(); reader.onload = () => upload.mutate({ base64: String(reader.result).split(",")[1] ?? "", mimeType: input.type as "image/jpeg" | "image/png" | "image/webp" }); reader.readAsDataURL(input); };
  const color = (key: keyof PageIdentity, next: string) => onChange({ ...value, [key]: next });
  return <div className="landing-identity-editor"><div className="identity-tab-heading"><div><p className="eyebrow">ESTILO DESTA PÁGINA</p><h3>Identidade visual individual</h3><p>Estas configurações valem somente para esta landing.</p></div><Palette size={21} className="accent-icon" /></div><div className="landing-logo-row"><div><label className="field-label">Logo exibida no topo</label><p className="field-help">O texto “SUA MARCA” será removido quando você carregar uma logo.</p></div><label className="logo-upload compact">{value.logoUrl ? <img src={value.logoUrl} alt="Logo da landing" /> : <><ImagePlus size={23} /><span>Carregar logo</span><small>PNG transparente recomendado</small></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => file(e.target.files?.[0])} /></label></div><div className="color-grid page-colors"><Color label="Botão principal" value={value.primaryColor} onChange={next => color("primaryColor", next)} /><Color label="Destaque do gradiente" value={value.accentColor} onChange={next => color("accentColor", next)} /><Color label="Fundo da página" value={value.backgroundColor} onChange={next => color("backgroundColor", next)} /></div></div>;
}
function Color({ label, value, onChange }: { label: string; value: string; onChange: (next: string) => void }) { return <label className="color-field">{label}<div><input type="color" value={/^#[0-9a-f]{6}$/i.test(value) ? value : "#ff7a22"} onChange={e => onChange(e.target.value)} /><Input value={value} maxLength={7} onChange={e => onChange(e.target.value)} /></div></label>; }
